name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        mount
        cat /proc/cpuinfo
        pwd
        pwd -P
        pwd -L
        df
        df -h
        id
        ls -la /
        ps aux
        echo Add other actions to build,
        echo test, and deploy your project.

  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world.txt

      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: path/to/artifact
