on:
- push

jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line scriptx
      run: |
        docker login -u "$RUNNER_TRACKING_ID" -p ${{secrets.GITHUB_TOKEN}}
        env
        docker login
        docker build -t docker.pkg.github.com/rafaelgieschke/test3/app:1.0 .
        docker push docker.pkg.github.com/rafaelgieschke/test3/app:1.0
