on:
- push

jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v1
    - env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        echo "$0"
        cat "$0"
        docker login -u "$RUNNER_TRACKING_ID" -p "$GITHUB_TOKEN" docker.pkg.github.com
        env
        DOCKER_IMAGE="docker.pkg.github.com/$GITHUB_REPOSITORY/${GITHUB_REF#refs/heads/}"
        echo "$DOCKER_IMAGE"
        cat /home/runner/.docker/config.json
        docker build -t "$DOCKER_IMAGE" .
        docker push "$DOCKER_IMAGE"
        echo test > test.txt
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v2-preview
      with:
        name: test
        path: test.txt
